### ISSUE TITLE
edify.io domain

### ISSUE THREAD

**Issue by targamedia** [javaSpock/edify.io#1]
Hey Andrew,

My name is Bobby Juncosa, and I own an advertising agency called Targa.  I have a client that would like to name their company Edify (Real Estate Technology).  Would you be willing to part with the edify.io domain?  They are a new company, but I know they are willing to put some money towards this.

If you're interested, please let me know how much you'd like to transfer the domain.

Thanks.

**Comment by javaSpock** [comment]
I was planning on using the domain for my own product, but since I haven't had time to get it off the ground, I'm open to offers. What does your client have in mind?

**Comment by targamedia** [comment]
They haven't said exactly. I have explained that the .io domain would be nice to have, but I'm not sure they "get it". 

I know they would pay a few hundred without thinking about it. Any more, and I'd have to really convince them .io was worth it. 

Is that what you were thinking?  Did you have a number in mind?

**Comment by javaSpock** [comment]
It's worth a lot more than that to me. You have to understand, edify.io is not just a domain, it's eventually going to be a brand name. The word "edify" has a very important meaning when it comes to homeschooling parents like me and my wife - it's what we strive to accomplish every single day. It's not just a business to us, it's a personal goal and a reminder of why we do what we do.

If it's all the same to your client, I would suggest they use another name or find another domain. Thanks anyway.

**Comment by targamedia** [comment]
I can understand that. I have projects of my own that I am passionate about at that level.

Is there a number that you feel is worth it to part with the .io domain?  It can’t hurt to present them with a number and see if they go for it.  I will communicate to them that this is not just a domain to you.

Not sure if it matters to you, but it looks like edify.eduation is available.  Is that something that would work for the brand you are building?

– Bobby
